version: '3.9'
services:
  app:
    container_name: lms_web_container
    platform: linux/amd64
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - TEST_POSTGRES_USER=${TEST_DB_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_DB_NAME}
      - TEST_DATABASE_HOST=${TEST_DB_HOST}
      - TEST_DATABASE_PORT=${TEST_DB_PORT}
    tty: true
    image: lms-user
    read_only: true
    pull_policy: never
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - default

  postgresdb:
    tty: true
    restart: always
    image: lms-pg
    container_name: lms-pg-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '1234:5432'
    networks:
      - default
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:   # add this section
  pgdata: 